SPACESHIP_PROMPT_ORDER=(
	user
	host
	dir
	git
	char
)

SPACESHIP_USER_SHOW="always"
SPACESHIP_USER_COLOR="yellow"
SPACESHIP_USER_SUFFIX=""
SPACESHIP_HOST_PREFIX="@"
SPACESHIP_HOST_SHOW="always"
SPACESHIP_HOST_COLOR="yellow"
SPACESHIP_DIR_PREFIX="["
SPACESHIP_DIR_COLOR="yellow"
SPACESHIP_DIR_SUFFIX="]"
SPACESHIP_GIT_PREFIX=" "
SPACESHIP_GIT_COLOR="cyan"
SPACESHIP_PROMPT_ADD_NEWLINE="false"
